config/routes.rb
Rails.application.routes.draw do
  root to: 'questions#index'

  resources :users, only: [:new, :create]

  resources :sessions, only: [:new, :create, :destroy]

  resources :questions do
    resources :answers
  end

  # resources :comments
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  belongs_to :user
  has_many :comments, as: :commentable
  has_many :votes, as: :voteable

  validates :body, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :commentable, polymorphic: true
  has_many :votes, as: :voteable

  validates :body, presence: true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  has_many :answers
  has_many :comments, as: :commentable
  has_many :votes, as: :voteable

  validates :title, :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :questions
  has_many :answers
  has_many :comments
  has_many :votes

  validates :username, :email, presence: true, uniqueness: true
  validate :has_password

  has_secure_password

  private

  def has_password
    if self.password == ""
      errors.add(:password, 'can\'t be empty')
    end
  end
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :user
  belongs_to :voteable, polymorphic: true


end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def new
    @answer = Answer.new
  end

  def create
    @question = Question.find(params[:question_id])
    @answer = @question.answers.new(answer_params)
    @answer.user = current_user

    if @answer.save
      redirect_to question_path(@question)
    else
      render "new"
    end
  end


  private

  def answer_params
    params.require(:answer).permit(:body)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
    @_current_user ||= session[:user_id] && User.find_by(id: session[:user_id])
  end
  helper_method :current_user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # def new
  # end

end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.all
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)
    @question.user = current_user

    if @question.save
      redirect_to @question
    else
      render "new"
    end
  end

  def show
    @question = Question.find(params[:id])
  end

  def edit
  end

  def update
  end

  def destroy
  end

private

  def question_params
    params.require(:question).permit(:title, :body, :user_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(email: params[:email])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render "new"
    end
  end

  def destroy
    current_user = session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render "new"
    end
  end

private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/answers/new.html.erb
<h1>Answer a Question</h1>

<%= form_for @answer, url: { action: "create"} do |f| %>
  <%= f.label :body, "Answer: " %>
  <%= f.text_field :body %>
  <br>
  <%= submit_tag "Submit Answer" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DbcRailsOverflow</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= link_to "home", root_path %> |
    <% if current_user%>
      <%= link_to "logout", session_path(current_user), method: :delete %> |
      <%= current_user.username %>
    <% else  %>
      <%= link_to "register", new_user_path %> |
      <%= link_to "login", new_session_path %>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/questions/index.html.erb
<h1>Questions Index</h1>

<% if current_user %>
  <%= link_to "New Question", new_question_path %>
<% end %>

<% if @questions %>
  <ul>
    <% @questions.each do |question| %>
      <li><%= link_to "#{question.title}", question_path(question) %></li>
    <% end %>
  </ul>
<% end %>

app/views/questions/new.html.erb
<h1>Create a Question</h1>

<%= form_for @question, url: { action: "create" } do |f| %>
  <%= f.label :title, "Title: " %>
  <%= f.text_field :title %>
  <br>
  <%= f.label :body, "Question: " %>
  <%= f.text_field :body %>
  <br>
  <%= submit_tag "Submit Question" %>
<% end %>

app/views/questions/show.html.erb
<h1><%= @question.title %></h1>
<p><%= @question.body %></p>
<p>Created by: <%= @question.user.username %></p>
<p>Created at: <%= @question.created_at %></p>


<%= link_to "Answer this question", new_question_answer_path(@question) %>
<br>
<hr>
<div>
  <% @question.answers.each do |answer| %>
    <article>
      <p><%= answer.body %></p>
      <p>Created by: <%= answer.user.username %></p>
      <p>Created at: <%= answer.created_at %></p>
      <hr>
    </article>
  <% end %>
</div>

app/views/users/new.html.erb
<h1>User Registration</h1>

<%= form_for @user, url: { action: "create" } do |f| %>
  <%= f.label :username, 'Username: ' %>
  <%= f.text_field :username %>
  <br>
  <%= f.label :email, 'Email: ' %>
  <%= f.email_field :email %>
  <br>
  <%= f.label :password, 'Password: ' %>
  <%= f.password_field :password %>
  <br>
  <%= submit_tag "Register" %>
<% end %>